### ISSUE TITLE
Descriptions about the Features in the  provided Datasets

### ISSUE THREAD

**Issue by assignmentupload** [srijankr/jodie#3]
Hi there,
1.	Just wondering where I can find the descriptions of each feature field of Wikipedia, Reddit and MOOC dataset used in the JODIE models.

2.    The MOOC dataset cannot be used with the “interaction_change_prediction” in the code.
Evaluate_interaction_prediction.py
if args.network == "mooc":
    print ("No interaction prediction for %s" % args.network)
sys.exit(0)
Could you provide some further explaination? 

Thanks a lot.

**Comment by assignmentupload** [comment]
I have found the answers in the paper. :)

**Comment by OliviaZhi** [comment]
Hi,

I have another question, but it seems that I cannot start a new issue. It would be greatly appreciated if someone can answer it.


So I'm wondering what if there are multiple uses, say, purchased some items (or click on the same video) at a certain time point (timestamp), or a user purchased multiple items in an order, will you put them in the same t-batch?  

Based on your approach, say if (u1,i1), (u1,i2), (u2,i2) interacted at the same time, if we assign them to t-batches using the following approach (code below), it's gonna assign them into three tbatches which will be affecting the embeddings. 

Will this affect the result? and do you think there should be someway to update them together?

Thanks!



```
 # CREATE T-BATCHES: ADD INTERACTION J TO THE CORRECT T-BATCH
            tbatch_to_insert = max(lib.tbatchid_user[userid], lib.tbatchid_item[itemid]) + 1
            lib.tbatchid_user[userid] = tbatch_to_insert
            lib.tbatchid_item[itemid] = tbatch_to_insert

            lib.current_tbatches_user[tbatch_to_insert].append(userid)
            lib.current_tbatches_item[tbatch_to_insert].append(itemid)
            lib.current_tbatches_feature[tbatch_to_insert].append(feature)
            lib.current_tbatches_interactionids[tbatch_to_insert].append(j)
            lib.current_tbatches_user_timediffs[tbatch_to_insert].append(user_timediff)
            lib.current_tbatches_item_timediffs[tbatch_to_insert].append(item_timediff)
            lib.current_tbatches_previous_item[tbatch_to_insert].append(user_previous_itemid_sequence[j])
```
